// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * 五个独立 sidebar,对应导航栏五个分区。
 * 每个分区用 autogenerated 从对应子目录生成,
 * 目录内用 _category_.json 控制顺序与中文标题。
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 教程 —— "带你走一遍"
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],

  // 编辑器手册(主角) —— "怎么用每个工具"
  editorSidebar: [{type: 'autogenerated', dirName: 'editors'}],

  // 开发文档 —— 给开发者
  devSidebar: [{type: 'autogenerated', dirName: 'dev'}],

  // 参考文档 —— "查事实"
  referenceSidebar: [{type: 'autogenerated', dirName: 'reference'}],

  // 玩家手册
  playerSidebar: [{type: 'autogenerated', dirName: 'player'}],
};

export default sidebars;
